const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
const connectDB = require("./config/db");
const authRoutes = require("./routes/authRoutes");
const expenseRoutes = require("./routes/expenseRoutes");
const incomeRoutes = require("./routes/incomeRoutes");
const investmentRoutes = require("./routes/investmentRoutes");
const dashboardRoutes = require("./routes/dashboardRoutes");

dotenv.config();
connectDB();
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || "https://money-wise-skrf.vercel.app/", credentials: true }));
app.use(express.json());
app.use("/api/auth", authRoutes);
app.use("/api/expenses", expenseRoutes);
app.use("/api/income", incomeRoutes);
app.use("/api/investments", investmentRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.get("/", (req, res) => res.json({ message: "MoneyWise API running! 💰" }));
app.use((req, res) => res.status(404).json({ message: "Route not found" }));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log("✅ Server running on http://localhost:" + PORT));